export const grammar = [
  "Abstract Nouns",
  "Active vs. Passive Voice",
  "Adjective Opposites",
  "Adjective Order",
  "Adjective-Preposition Collocations",
  "Adjective-Noun Collocations",
  "Adjectives",
  "Adjectives of Feeling & Emotion",
  "Adjectives of Opinion",
  "Adjectives of Quantity",
  "Adverb Order",
  "Adverb-Adjective Collocations",
  "Adverbial Clauses",
  "Adverbial Phrases",
  "Adverbs of Affirmation & Negation",
  "Adverbs of Degree",
  "Adverbs of Frequency",
  "Adverbs of Manner",
  "Adverbs of Place",
  "Adverbs of Time",
  "Articles - a, an, the",
  "Be Going To & Present Continuous",
  "Be Going To Statements",
  "Be Going To Wh Questions",
  "Be Going To Yes/No Questions",
  "Causative Verbs",
  "Common & Proper Nouns",
  "Comparatives",
  "Comparatives & Superlatives",
  "Compound Adjectives",
  "Compound Nouns",
  "Concrete Nouns",
  "Conjunctions",
  "Continuous",
  "Countable & Uncountable Nouns",
  "Demonstrative Adjectives",
  "Demonstrative Pronouns",
  "Dependent Prepositions",
  "First Conditional",
  "Future Continuous",
  "Future Continuous vs. Future Perfect",
  "Future Perfect Continuous",
  "Future Perfect Simple",
  "Future Simple",
  "Future Tenses",
  "Future Time Clauses",
  "Gerunds & Infinitives",
  "Have Got & Has Got",
  "I wish & If only",
  "Imperatives",
  "Indefinite Pronouns",
  "Intensifiers & Mitigators",
  "Interjections",
  "Irregular Verbs",
  "Mixed Conditionals",
  "Modal Verbs of Ability",
  "Modals of Deduction & Speculation",
  "Modals of Necessity",
  "Modals of Obligation & Prohibition",
  "Modals of Possibility & Certainty",
  "Narrative Tenses",
  "Noun Clauses",
  "Noun Phrases",
  "Onomatopoeia",
  "Parts of Speech",
  "Passive Voice",
  "Past Continuous",
  "Past Perfect",
  "Past Perfect Continuous",
  "Past Perfect Simple & Continuous",
  "Past Simple Affirmative & Negative",
  "Past Simple Passive",
  "Past Simple Regular Verbs",
  "Past Simple Was and Were",
  "Past Simple Wh Questions",
  "Past Simple Yes/No Questions",
  "Past Simple vs. Past Continuous",
  "Past Simple vs. Present Perfect",
  "Past Tense Review",
  "Phrasal Verbs",
  "Possessives",
  "Prefixes",
  "Prepositions of Movement",
  "Prepositions of Place",
  "Prepositions of Time",
  "Present Continuous",
  "Present Perfect",
  "Present Perfect - Ever and Never",
  "Present Perfect - For and Since",
  "Present Perfect - Just, Yet & Already",
  "Present Perfect Continuous",
  "Present Simple Affirmative & Negative",
  "Present Simple Passive",
  "Present Simple Wh Questions",
  "Present Simple Yes/No Questions",
  "Present Simple vs. Present Continuous",
  "Present Simple vs. Present Perfect",
  "Present Tense Review",
  "Proper Adjectives",
  "Quantifiers",
  "Question Words",
  "Reflexive Pronouns",
  "Relative Clauses",
  "Reported Speech",
  "Second Conditional",
  "Sense Verbs and Adjectives",
  "Singular & Plural Nouns",
  "So and Such",
  "Subject & Object Pronouns",
  "Subject-Verb Agreement",
  "Suffixes",
  "Superlatives",
  "Tag Questions",
  "There is & There are",
  "Third Conditional",
  "Too and Enough",
  "Transition Words",
  "Used to",
  "Verb to be",
  "Verb-Noun Collocations",
  "Verbs",
  "Wh Questions",
  "Zero Conditional",
];
